version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin1
      # MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: green_city_db
    ports:
      - 27017:27017
    volumes:
      - ./green_city_db:/data/db